server:
  port: ${PORT_GATEWAY}

spring:
  application:
    name: ${GATEWAY_SERVICE}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:-"*"}
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: ${CORS_ALLOWED_HEADERS:-"*"}
            allowCredentials: ${CORS_ALLOW_CREDENTIALS:-false}
            maxAge: ${CORS_MAX_AGE:-3600}
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: 'http://${USER_SERVICE}:${PORT_USER}'
          predicates:
            - Path=/api/auth/**
        - id: mail
          uri: 'http://${MAIL_SERVICE}:${PORT_MAIL}'
          predicates:
            - Path=/api/v1/emails/**
        - id: cloud
          uri: 'http://${CLOUD_SERVICE}:${PORT_CLOUD}'
          predicates:
            - Path=/api/v1/cloud/**

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}:${PORT_EUREKA}/eureka/

app:
  jwt:
    secret: ${JWT_SECRET}