server:
  port: ${PORT_GATEWAY}

spring:
  application:
    name: ${GATEWAY_SERVICE}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:-"*"}
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: ${CORS_ALLOWED_HEADERS:-"*"}
            allowCredentials: ${CORS_ALLOW_CREDENTIALS:-false}
            maxAge: ${CORS_MAX_AGE:-3600}
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}:${PORT_EUREKA}/eureka/

app:
  jwt:
    secret: ${JWT_SECRET}

microservicios:
  enable-user: ${ENABLE_USER}
  enable-mail: ${ENABLE_MAIL}
  enable-cloud: ${ENABLE_CLOUD}