server:
  port: ${PORT_EUREKA}

spring:
  application:
    name: ${EUREKA_SERVICE}

eureka:
  instance:
    hostname: ${EUREKA_SERVICE}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}:${PORT_EUREKA}/eureka/