server:
  port: ${PORT_MAIL}

spring:
  application:
    name: ${MAIL_SERVICE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVICE}:${PORT_DB}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${EUREKA_SERVICE}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}:${PORT_EUREKA}/eureka
