server:
  port: ${PORT_CLOUD}

spring:
  application:
    name: ${CLOUD_SERVICE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVICE}:${PORT_DB}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

eureka:
  instance:
    hostname: ${EUREKA_SERVICE}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}:${EUREKA_PORT}/eureka

# Configuración específica para integraciones
cloud-integration:
  providers:
    google-drive:
      enabled: ${GOOGLE_DRIVE_ENABLED}
    dropbox:
      enabled: ${DROPBOX_ENABLED}
    onedrive:
      enabled: ${ONEDRIVE_ENABLED}
    notion:
      enabled: ${NOTION_ENABLED}

# Notion API Configuration
notion:
  api:
    version: ${NOTION_API_VERSION}
  client:
    id: ${NOTION_CLIENT_ID}
    secret: ${NOTION_CLIENT_SECRET}
  redirect:
    uri: ${NOTION_REDIRECT_URI}
  auth:
    success:
      redirect: ${NOTION_SUCCESS_REDIRECT}
    failure:
      redirect: ${NOTION_FAILURE_REDIRECT}