server:
  port: ${PORT_CONFIG}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations